
variables:
  base_folder: &base_folder "/run/user/1000/gvfs/smb-share:server=filer2-imn,share=t4/Julien/MarcAnalysis"

#Information about the input data (not the process). Should almost never change.
input:
  - dataframe: electrophisiology
    files:
      - file_scan:
          path: *base_folder "/Inputs/MonkeyData4Review":
          cached_into: *base_folder "/.cache/electrophisiology/MonkeyData4Review_scan.txt"
          rescan: No
          file_patterns: #relative to path
            - "{condition}/{subject}/{structure}/{date}/{unit}.mat"
    metadata: null #A list of tsv files possibly ith join keys. Not handled yet
    columns: 
      condition: "{condition}"
      subject: "{subject}"
      structure: "{structure}"
      date: "{date}"
      unit: "{unit}"
      sample_id: "MonkeyData4Review/{condition}/{subject}/{structure}/{date}/{unit}"
      group_id: "{subject}, {structure}"
      sample_path: *base_folder "/Inputs/MonkeyData4Review/{file}"
      fs: 25000

#Subselecting part of the input on which to run
run_selection:
  - dataframes: all #Applies to all dataframes
    group_id: 
      range: null
      group_range: [0, 2]
      in: null
      notin: null
     
run_params: #Format will need to change to handle sample level run parameters
  variables:
    base_folder: *base_folder
    signal: ["lfp", "mu"]
  rm_artefacts:
    variables: 
      base_folder: *base_folder
    clean_params:
      version: 2
      deviation_factor: 5
      min_length: 0.003
      shoulder_width: 1
      join_width: 3
      recursive: True
      replace_type: affine
    figure_params: 
      version: 1
      wdith: 10
      height: 10
      dpi: 100
      down_sampling: 10
  extract_signals:
    variables: 
      base_folder: *base_folder
    lfp_params:
      version: 1
      filter_freq: 200
      order: 3
      out_fs: 500
    mu_params:
      version: 1
      method: "abs"
      filter_low_freq: 300
      filter_high_freq: 6000
      filter_refreq: 1000
      order: 3
      out_fs: 1000
    spike_params:
      method: "precomputed"
  pwelch:
    variables:
      base_folder: *base_folder
      signal: ["lfp", "mu"]



file_structure:
  rm_artefacts:
    cleaned_path: "{base_folder}/Cleaned/{rm_artefacts.clean_params_str}/results/{electrophisiology.sample_id}_signal.npy"
    summary_path: "{base_folder}/Cleaned/{rm_artefacts.clean_params_str}/results/{electrophisiology.sample_id}_summary.tsv"
    figure_path:  "{base_folder}/Cleaned/{rm_artefacts.clean_params_str}/figures/{electrophisiology.sample_id}_fp={rm_artefacts.figure_params_str}.png"
  extract_signals:
    signal_path: *base_folder "/Signals/{signal}/{lfp_params_str}/{clean_params_str}/results/{sample_id}_signal.npy"
    signal_metadata_path: *base_folder "/Signals/{signal}/{lfp_params_str}/{clean_params_str}/results/{sample_id}_metadata.json"
  pwelch_analysis:
    pwelch_path: *base_folder "/Pwelch/{pwelch_params_str}/{signal}/{lfp_params_str}/{clean_params_str}/results/{sample_id}_signal.npy"
